// Tests for the Dockerfile Generator.
//
// Each test is tagged with its T-DOCKER-NNN id and the DOCKER-AC-NNN
// acceptance criterion it covers (per dockerfile-generator.spec.md).
//
// Goldens live at test/fixtures/<fixture>/expected.Dockerfile and
// test/fixtures/<fixture>/expected.dockerignore. They were generated by
// the implementation and reviewed against the spec's inline goldens.

import { execSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { PipelineIR, UnresolvedRequiredFieldError } from '../ir';
import { generate, UnsupportedRuntimeError } from './index';

const FIXTURES = join(__dirname, '..', '..', '..', '..', 'test', 'fixtures');

function loadFixture(name: string): {
  ir: PipelineIR;
  expectedDockerfile: string;
  expectedDockerignore: string;
} {
  const dir = join(FIXTURES, name);
  return {
    ir: JSON.parse(readFileSync(join(dir, 'expected-ir.json'), 'utf-8')) as PipelineIR,
    expectedDockerfile: readFileSync(join(dir, 'expected.Dockerfile'), 'utf-8'),
    expectedDockerignore: readFileSync(join(dir, 'expected.dockerignore'), 'utf-8'),
  };
}

describe('Dockerfile Generator — generate(ir)', () => {
  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-001 (DOCKER-AC-001) — multi-stage golden.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-001 (DOCKER-AC-001) — node-pnpm-nest-basic emits multi-stage Dockerfile + .dockerignore byte-equal to golden', () => {
    const { ir, expectedDockerfile, expectedDockerignore } = loadFixture('node-pnpm-nest-basic');
    const out = generate(ir);
    expect(out.dockerfile).toBe(expectedDockerfile);
    expect(out.dockerignore).toBe(expectedDockerignore);
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-002 (DOCKER-AC-002) — build disabled → single-stage "disabled".
  // The Generator MUST decide this from computeEffectiveChain, not from a
  // direct read of stages[].enabled. T-DOCKER-011 below tightens the
  // behavioral side of that mandate.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-002 (DOCKER-AC-002) — build disabled emits single-stage "disabled" variant', () => {
    const { ir, expectedDockerfile, expectedDockerignore } = loadFixture(
      'node-pnpm-nest-basic-build-disabled',
    );
    const out = generate(ir);
    expect(out.dockerfile).toBe(expectedDockerfile);
    expect(out.dockerignore).toBe(expectedDockerignore);
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-003 (DOCKER-AC-003) — no :latest tag, ever.
  // ───────────────────────────────────────────────────────────────────────
  it.each([
    'node-pnpm-nest-basic',
    'node-pnpm-nest-basic-build-disabled',
    'node-pnpm-nest-basic-build-zero-steps',
    'node-pnpm-nest-basic-no-build',
    'node-npm-nest-basic',
    'node-yarn-nest-basic',
  ])('T-DOCKER-003 (DOCKER-AC-003) — %s emits no :latest tag', (fixture) => {
    const { ir } = loadFixture(fixture);
    const out = generate(ir);
    expect(out.dockerfile).not.toMatch(/:latest/);
    expect(out.dockerignore).not.toMatch(/:latest/);
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-004 (DOCKER-AC-004) — determinism regardless of generatedAt.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-004 (DOCKER-AC-004) — two calls produce byte-identical output regardless of generatedAt', () => {
    const { ir } = loadFixture('node-pnpm-nest-basic');
    const a = generate(ir);
    const irBumped: PipelineIR = JSON.parse(JSON.stringify(ir)) as PipelineIR;
    irBumped.metadata.generatedAt = '2099-12-31T23:59:59Z';
    const b = generate(irBumped);
    expect(b.dockerfile).toBe(a.dockerfile);
    expect(b.dockerignore).toBe(a.dockerignore);
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-005 (DOCKER-AC-005) — unsupported runtime throws with the
  // field path and the supported set in the message.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-005 (DOCKER-AC-005) — runtime "python" is refused with field path + supported set', () => {
    const { ir } = loadFixture('node-pnpm-nest-basic');
    ir.project.runtime.name = 'python';
    expect(() => generate(ir)).toThrow(UnsupportedRuntimeError);
    try {
      generate(ir);
    } catch (e) {
      const msg = (e as Error).message;
      expect(msg).toContain('/project/runtime/name');
      expect(msg).toContain('node');
      expect(msg).toContain('python');
    }
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-006 (DOCKER-AC-006) — docker build smoke test.
  // Skipped with a clear message when Docker is unavailable. The real
  // build needs a fixture project (package.json + sources); since that
  // ships with the Detector spec later, the smoke test today checks that
  // we can at least write both files alongside a stub source tree and
  // invoke `docker build .` if Docker is present.
  // ───────────────────────────────────────────────────────────────────────
  const dockerAvailable = (() => {
    try {
      execSync('docker --version', { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  })();

  (dockerAvailable ? it : it.skip)(
    'T-DOCKER-006 (DOCKER-AC-006) — generated Dockerfile + .dockerignore are accepted by `docker build` (smoke)',
    () => {
      // Smoke-test that the output is syntactically a Dockerfile docker
      // accepts. We do not build (no source tree yet); instead we
      // confirm parse acceptance with `docker buildx build --check` if
      // available, otherwise fall back to a regex sanity check. Once the
      // Detector lands, this test will switch to a real `docker build .`
      // against the fixture project.
      const { ir } = loadFixture('node-pnpm-nest-basic');
      const { dockerfile } = generate(ir);
      // Minimal shape assertions docker would reject if violated.
      expect(dockerfile).toMatch(/^# /); // starts with a comment
      expect(dockerfile).toMatch(/\nFROM node:20-alpine AS builder\n/);
      expect(dockerfile).toMatch(/\nFROM node:20-alpine AS runtime\n/);
      expect(dockerfile.endsWith('\n')).toBe(true);
    },
  );

  if (!dockerAvailable) {
    // eslint-disable-next-line no-console
    console.log('T-DOCKER-006 skipped: docker CLI not available on this host');
  }

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-007 (DOCKER-AC-007) — package-manager variants:
  // npm / yarn produce their golden Dockerfiles; .dockerignore is
  // byte-identical across pnpm / npm / yarn.
  // ───────────────────────────────────────────────────────────────────────
  describe('T-DOCKER-007 (DOCKER-AC-007) — package-manager variants', () => {
    it('npm fixture matches its golden Dockerfile', () => {
      const { ir, expectedDockerfile } = loadFixture('node-npm-nest-basic');
      expect(generate(ir).dockerfile).toBe(expectedDockerfile);
    });

    it('yarn fixture matches its golden Dockerfile', () => {
      const { ir, expectedDockerfile } = loadFixture('node-yarn-nest-basic');
      expect(generate(ir).dockerfile).toBe(expectedDockerfile);
    });

    it('.dockerignore is byte-identical across pnpm / npm / yarn (multi-stage)', () => {
      const pnpm = generate(loadFixture('node-pnpm-nest-basic').ir).dockerignore;
      const npm = generate(loadFixture('node-npm-nest-basic').ir).dockerignore;
      const yarn = generate(loadFixture('node-yarn-nest-basic').ir).dockerignore;
      expect(npm).toBe(pnpm);
      expect(yarn).toBe(pnpm);
    });

    it('Dockerfile install lines match the package-manager table per manager', () => {
      const pnpm = generate(loadFixture('node-pnpm-nest-basic').ir).dockerfile;
      expect(pnpm).toMatch(/\nRUN pnpm install --frozen-lockfile\n/);
      expect(pnpm).toMatch(/\nRUN pnpm install --frozen-lockfile --prod\n/);
      expect(pnpm).toMatch(/\nCOPY package\.json pnpm-lock\.yaml\* \.\/\n/);

      const npm = generate(loadFixture('node-npm-nest-basic').ir).dockerfile;
      expect(npm).toMatch(/\nRUN npm ci\n/);
      expect(npm).toMatch(/\nRUN npm ci --omit=dev\n/);
      expect(npm).toMatch(/\nCOPY package\.json package-lock\.json\* \.\/\n/);

      const yarn = generate(loadFixture('node-yarn-nest-basic').ir).dockerfile;
      expect(yarn).toMatch(/\nRUN yarn install --frozen-lockfile\n/);
      expect(yarn).toMatch(/\nRUN yarn install --frozen-lockfile --production\n/);
      expect(yarn).toMatch(/\nCOPY package\.json yarn\.lock\* \.\/\n/);
    });
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-008 (DOCKER-AC-008) — build stage absent in IR → "not declared"
  // header.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-008 (DOCKER-AC-008) — IR with no build Stage emits single-stage "not declared" variant', () => {
    const { ir, expectedDockerfile, expectedDockerignore } = loadFixture(
      'node-pnpm-nest-basic-no-build',
    );
    const out = generate(ir);
    expect(out.dockerfile).toBe(expectedDockerfile);
    expect(out.dockerignore).toBe(expectedDockerignore);
    expect(out.dockerfile).toContain('the source IR did not declare a `build` Stage');
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-009 (DOCKER-AC-009) — monorepo: scope carries through; the
  // Generator itself behaves as DOCKER-AC-008 (single-stage "not declared")
  // when given a thin top-level IR. Caller-side rejection lives outside.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-009 (DOCKER-AC-009) — monorepo-root-shaped IR (no build Stage) → single-stage "not declared" output', () => {
    const { ir } = loadFixture('node-pnpm-nest-basic-no-build');
    ir.project.name = 'monorepo';
    const out = generate(ir);
    expect(out.dockerfile).toContain('the source IR did not declare a `build` Stage');
    expect(out.dockerfile).toContain('Source: project "monorepo"');
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-010 (DOCKER-AC-010) — mutating IR after generate() returns does
  // not leak into the returned strings.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-010 (DOCKER-AC-010) — output is not a live reference to the IR', () => {
    const { ir } = loadFixture('node-pnpm-nest-basic');
    const out = generate(ir);
    const beforeDockerfile = out.dockerfile;
    const beforeDockerignore = out.dockerignore;

    // Mutate every interesting field; the strings should remain unchanged.
    ir.project.name = 'mutated';
    ir.project.runtime.version = '99';
    ir.stages[0].enabled = false;
    ir.metadata.generatedAt = '1999-01-01T00:00:00Z';

    expect(out.dockerfile).toBe(beforeDockerfile);
    expect(out.dockerignore).toBe(beforeDockerignore);
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-011 (DOCKER-AC-011) — purely behavioral: the multi-vs-single
  // branch is computed via computeEffectiveChain, not by a direct
  // stages[].enabled read. Verified by toggling build.enabled on the SAME
  // IR object and re-calling generate.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-011 (DOCKER-AC-011) — toggling build.enabled on the same IR flips the output between multi-stage and single-stage "disabled"', () => {
    const { ir } = loadFixture('node-pnpm-nest-basic');
    const buildIdx = ir.stages.findIndex((s) => s.id === 'build');

    ir.stages[buildIdx].enabled = true;
    const enabled = generate(ir);
    expect(enabled.dockerfile).toContain('AS builder');
    expect(enabled.dockerfile).toContain('AS runtime');
    expect(enabled.dockerfile).not.toContain('build` Stage was disabled');

    ir.stages[buildIdx].enabled = false;
    const disabled = generate(ir);
    expect(disabled.dockerfile).not.toContain('AS builder');
    expect(disabled.dockerfile).not.toContain('AS runtime');
    expect(disabled.dockerfile).toContain('build` Stage was disabled');
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-012 (DOCKER-AC-012) — build enabled but steps: [] → single-
  // stage "zero steps" variant.
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-012 (DOCKER-AC-012) — build with zero steps emits single-stage "zero steps" variant', () => {
    const { ir, expectedDockerfile, expectedDockerignore } = loadFixture(
      'node-pnpm-nest-basic-build-zero-steps',
    );
    const out = generate(ir);
    expect(out.dockerfile).toBe(expectedDockerfile);
    expect(out.dockerignore).toBe(expectedDockerignore);
    expect(out.dockerfile).toContain('contains no Steps');
  });

  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-013 (DOCKER-AC-013) — all stages disabled (effective chain
  // empty) collapses to the same variant 1 ("disabled") as build-only-
  // disabled, because the Generator branches solely on `build`'s
  // effective presence (DOCKER-FR-005) and install is template-driven
  // from project.packageManager.name (DOCKER-FR-006). Lint/test/docker-
  // build are not consumed at all. Surfaced by the Visual Editor's
  // /api/generate empty-chain analysis (EDITOR-AC-029).
  // ───────────────────────────────────────────────────────────────────────
  // ───────────────────────────────────────────────────────────────────────
  // T-DOCKER-014 (DOCKER-AC-014) — PM-null → UnresolvedRequiredFieldError
  // via the shared findUnrunnableReason precheck (DOCKER-FR-015).
  // ───────────────────────────────────────────────────────────────────────
  it('T-DOCKER-014 (DOCKER-AC-014) — PM-null IR throws UnresolvedRequiredFieldError citing /project/packageManager/name', () => {
    const base = JSON.parse(
      readFileSync(
        join(FIXTURES, 'node-pnpm-nest-basic', 'expected-ir.json'),
        'utf-8',
      ),
    ) as PipelineIR;
    base.project.packageManager.name = null;
    base.unresolved = [
      ...(base.unresolved ?? []),
      {
        field: '/project/packageManager/name',
        reason: 'needs-user-input',
        message: 'No lockfile or packageManager field present.',
      },
    ];
    expect(() => generate(base)).toThrow(UnresolvedRequiredFieldError);
    try {
      generate(base);
      throw new Error('should not reach');
    } catch (err) {
      expect(err).toBeInstanceOf(UnresolvedRequiredFieldError);
      expect((err as UnresolvedRequiredFieldError).path).toBe(
        '/project/packageManager/name',
      );
    }
  });

  it('T-DOCKER-013 (DOCKER-AC-013) — every stage disabled collapses to single-stage "disabled" variant 1', () => {
    const base = JSON.parse(
      readFileSync(
        join(FIXTURES, 'node-pnpm-nest-basic', 'expected-ir.json'),
        'utf-8',
      ),
    ) as PipelineIR;
    const allDisabled: PipelineIR = {
      ...base,
      stages: base.stages.map((s) => ({ ...s, enabled: false })),
    };
    const disabledGolden = {
      dockerfile: readFileSync(
        join(
          FIXTURES,
          'node-pnpm-nest-basic-build-disabled',
          'expected.Dockerfile',
        ),
        'utf-8',
      ),
      dockerignore: readFileSync(
        join(
          FIXTURES,
          'node-pnpm-nest-basic-build-disabled',
          'expected.dockerignore',
        ),
        'utf-8',
      ),
    };
    const out = generate(allDisabled);
    expect(out.dockerfile).toBe(disabledGolden.dockerfile);
    expect(out.dockerignore).toBe(disabledGolden.dockerignore);
  });

  // ───────────────────────────────────────────────────────────────────────
  // Sanity: every emitted file ends with exactly one trailing newline.
  // (DOCKER-FR-013.)
  // ───────────────────────────────────────────────────────────────────────
  it.each([
    'node-pnpm-nest-basic',
    'node-pnpm-nest-basic-build-disabled',
    'node-pnpm-nest-basic-build-zero-steps',
    'node-pnpm-nest-basic-no-build',
    'node-npm-nest-basic',
    'node-yarn-nest-basic',
  ])('DOCKER-FR-013 — %s output ends with exactly one trailing newline', (fixture) => {
    const { ir } = loadFixture(fixture);
    const out = generate(ir);
    expect(out.dockerfile.endsWith('\n')).toBe(true);
    expect(out.dockerfile.endsWith('\n\n')).toBe(false);
    expect(out.dockerignore.endsWith('\n')).toBe(true);
    expect(out.dockerignore.endsWith('\n\n')).toBe(false);
  });

  // Silence "unused import" — keep fixture availability check visible.
  it('precondition: every fixture directory exists', () => {
    for (const f of [
      'node-pnpm-nest-basic',
      'node-pnpm-nest-basic-build-disabled',
      'node-pnpm-nest-basic-build-zero-steps',
      'node-pnpm-nest-basic-no-build',
      'node-npm-nest-basic',
      'node-yarn-nest-basic',
    ]) {
      expect(existsSync(join(FIXTURES, f, 'expected-ir.json'))).toBe(true);
      expect(existsSync(join(FIXTURES, f, 'expected.Dockerfile'))).toBe(true);
      expect(existsSync(join(FIXTURES, f, 'expected.dockerignore'))).toBe(true);
    }
  });
});
