// Dockerfile Generator — strict implementation of dockerfile-generator.spec.md.
//
// Public surface:
//   generate(ir): { dockerfile: string; dockerignore: string }
//
// Branching rules (Design Decision 5):
//   - `build` in the effective chain AND has ≥ 1 Step → multi-stage Dockerfile.
//   - `build` in the effective chain but has 0 Steps  → single-stage, "zero-steps" header.
//   - `build` in the IR but `enabled: false`          → single-stage, "disabled" header.
//   - `build` not present in the IR at all            → single-stage, "not-declared" header.
//
// The branch is computed from `computeEffectiveChain(ir)` (DOCKER-FR-002 /
// DOCKER-NFR-004). The generator never reads `stages[].enabled` directly.

import { sanitizeForComment } from '../docker-naming';
import {
  computeEffectiveChain,
  findUnrunnableReason,
  PackageManagerName,
  PipelineIR,
  Stage,
  UnresolvedRequiredFieldError,
} from '../ir';
import { UnsupportedRuntimeError } from './errors';
import { BuildMode, DockerfileArtifacts, SUPPORTED_RUNTIMES, SupportedRuntime } from './types';

export function generate(ir: PipelineIR): DockerfileArtifacts {
  // DOCKER-FR-NNN / DOCKER-AC-014 — single-source-of-truth precheck via
  // findUnrunnableReason. PM-null or runtime-version-null (paired with
  // an unresolved entry, so validate() passes) throws here rather than
  // producing a malformed Dockerfile. Empty effective chain is NOT a
  // generator-side refusal: the single-stage "disabled" / "not declared"
  // variants are the documented behavior for that shape.
  const unrunnable = findUnrunnableReason(ir);
  if (unrunnable !== null && unrunnable.kind === 'unresolved-required-field') {
    throw new UnresolvedRequiredFieldError(unrunnable.field);
  }

  // DOCKER-FR-010 / DOCKER-AC-005 — supported runtime gate.
  if (!isSupportedRuntime(ir.project.runtime.name)) {
    throw new UnsupportedRuntimeError(ir.project.runtime.name);
  }

  const mode = resolveBuildMode(ir);

  const dockerfile = mode === 'multi-stage' ? renderMultiStage(ir) : renderSingleStage(ir, mode);
  const dockerignore = mode === 'multi-stage' ? renderDockerignoreMulti() : renderDockerignoreSingle();

  return { dockerfile, dockerignore };
}

function isSupportedRuntime(name: unknown): name is SupportedRuntime {
  return typeof name === 'string' && (SUPPORTED_RUNTIMES as readonly string[]).includes(name);
}

function resolveBuildMode(ir: PipelineIR): BuildMode {
  // DOCKER-FR-002: branch is computed from the effective chain — never from
  // stages[].enabled directly.
  const effective = computeEffectiveChain(ir);
  const effectiveBuild = effective.find((s) => s.id === 'build');

  if (effectiveBuild !== undefined) {
    return effectiveBuild.steps.length > 0 ? 'multi-stage' : 'single-zero-steps';
  }

  // Not in effective chain. Distinguish "in IR but disabled" from "not in IR
  // at all" by inspecting the document directly. (Reading enabled here is
  // permitted: it determines the HEADER variant only, not the multi-vs-single
  // branch — which has already been settled by computeEffectiveChain above.)
  const inDoc = ir.stages.find((s) => s.id === 'build');
  return inDoc === undefined ? 'single-not-declared' : 'single-disabled';
}

// ─────────────────────────────────────────────────────────────────────────────
// Multi-stage template
// ─────────────────────────────────────────────────────────────────────────────
function renderMultiStage(ir: PipelineIR): string {
  const baseImage = baseImageFor(ir);
  const pm = ir.project.packageManager.name as PackageManagerName;
  const lockfile = lockfileFor(pm);
  const corepackLine = needsCorepack(pm) ? 'RUN corepack enable\n\n' : '';
  const frozen = usesFrozenInstall(ir);
  const installFull = installCommand(pm, /* prodOnly */ false, frozen);
  const installProd = installCommand(pm, /* prodOnly */ true, frozen);
  const buildCmd = buildCommandFromStage(getBuildStage(ir));
  const cmd = conventionalCmd(ir);

  const corepackComment = needsCorepack(pm)
    ? `# Enable corepack so the pinned ${pm} version is available.\n`
    : '';

  return (
    `# Generated by pipe-editor v0.1.0 from a Pipeline IR.\n` +
    `# Source: project "${sanitizeForComment(ir.project.name)}" — runtime: ${ir.project.runtime.name} ${ir.project.runtime.version} — packageManager: ${pm} ${ir.project.packageManager.version}.\n` +
    `# This Dockerfile is portable: \`docker build .\` works with no pipe-editor\n` +
    `# tooling present. A companion \`.dockerignore\` is generated alongside.\n` +
    `\n` +
    `# ─── Builder stage ──────────────────────────────────────────────────────────\n` +
    `FROM ${baseImage} AS builder\n` +
    `\n` +
    `WORKDIR /app\n` +
    `\n` +
    corepackComment +
    corepackLine +
    `# Copy manifest and lockfile first so dependency installation caches\n` +
    `# independently of source changes. The trailing \`*\` makes the lockfile\n` +
    `# optional: without it, \`docker build\` fails outright on a project that\n` +
    `# has not committed one (GEN-04).\n` +
    `COPY package.json ${lockfile}* ./\n` +
    `\n` +
    `# Install all dependencies (including dev) for the build.\n` +
    `RUN ${installFull}\n` +
    `\n` +
    `# Copy the rest of the project source. The companion .dockerignore excludes\n` +
    `# node_modules, dist, .git, .env, etc., so this COPY is safe.\n` +
    `COPY . .\n` +
    `\n` +
    `# Build command from the IR's \`build\` Stage.\n` +
    `RUN ${buildCmd}\n` +
    `\n` +
    `# ─── Runtime stage ──────────────────────────────────────────────────────────\n` +
    `FROM ${baseImage} AS runtime\n` +
    `\n` +
    `WORKDIR /app\n` +
    `\n` +
    corepackLine +
    `# Install production-only dependencies. We re-install from the lockfile\n` +
    `# here rather than \`COPY --from=builder node_modules\` and prune: a fresh\n` +
    `# install is deterministic in one command, while prune semantics differ\n` +
    `# subtly across package managers and versions.\n` +
    `COPY package.json ${lockfile}* ./\n` +
    `RUN ${installProd}\n` +
    `\n` +
    `# Copy build artifacts from the builder stage.\n` +
    `#\n` +
    `# ASSUMPTION (GEN-03): your build writes to \`dist/\`. pipe-editor detects\n` +
    `# from manifests only and the Pipeline IR does not carry a build-output\n` +
    `# directory, so this path is a convention, not an observation. If your\n` +
    `# build writes somewhere else — \`build/\`, \`out/\`, \`.output/\` — change\n` +
    `# BOTH the line below and the CMD at the end of this file. The Pipeline\n` +
    `# Doctor reports this assumption on every multi-stage build.\n` +
    `COPY --from=builder /app/dist ./dist\n` +
    `\n` +
    `# CMD inferred from the Node/NestJS convention (DOCKER-LIMIT-001).\n` +
    `CMD ${cmd}\n`
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Single-stage template (three header variants share the same body)
// ─────────────────────────────────────────────────────────────────────────────
function renderSingleStage(ir: PipelineIR, mode: Exclude<BuildMode, 'multi-stage'>): string {
  const baseImage = baseImageFor(ir);
  const pm = ir.project.packageManager.name as PackageManagerName;
  const lockfile = lockfileFor(pm);
  const corepackLine = needsCorepack(pm) ? 'RUN corepack enable\n\n' : '';
  const installProd = installCommand(pm, /* prodOnly */ true, usesFrozenInstall(ir));
  const cmd = conventionalCmd(ir);

  return (
    headerFor(ir, mode) +
    `\n` +
    `FROM ${baseImage}\n` +
    `\n` +
    `WORKDIR /app\n` +
    `\n` +
    corepackLine +
    `# Install production-only dependencies.\n` +
    `COPY package.json ${lockfile}* ./\n` +
    `RUN ${installProd}\n` +
    `\n` +
    `# Copy the project source. The companion .dockerignore excludes\n` +
    `# node_modules, .git, .env, etc., but intentionally keeps \`dist/\` so\n` +
    `# pre-built artifacts reach the image.\n` +
    `COPY . .\n` +
    `\n` +
    `# CMD inferred from the Node/NestJS convention (DOCKER-LIMIT-001).\n` +
    `CMD ${cmd}\n`
  );
}

function headerFor(ir: PipelineIR, mode: Exclude<BuildMode, 'multi-stage'>): string {
  const top =
    `# Generated by pipe-editor v0.1.0 from a Pipeline IR.\n` +
    `# Source: project "${sanitizeForComment(ir.project.name)}" — runtime: ${ir.project.runtime.name} ${ir.project.runtime.version} — packageManager: ${ir.project.packageManager.name} ${ir.project.packageManager.version}.\n` +
    `#\n`;

  const body =
    mode === 'single-disabled'
      ? `# NOTE: the \`build\` Stage was disabled in the Pipeline IR; the image\n` +
        `# assumes pre-built artifacts (e.g. \`dist/\`) exist in the source. If they\n` +
        `# do not, the resulting image will not be runnable. To restore a build\n` +
        `# step, re-enable the \`build\` Stage in the Visual Editor. The companion\n` +
        `# .dockerignore intentionally does NOT exclude \`dist/\`.\n`
      : mode === 'single-zero-steps'
        ? `# NOTE: the \`build\` Stage is declared in the IR but contains no Steps;\n` +
          `# nothing was built. The image assumes pre-built artifacts (e.g.\n` +
          `# \`dist/\`) exist in the source. If they do not, the resulting image\n` +
          `# will not be runnable. The companion .dockerignore intentionally does\n` +
          `# NOT exclude \`dist/\`.\n`
        : // single-not-declared
          `# NOTE: the source IR did not declare a \`build\` Stage; nothing was built.\n` +
          `# The image assumes pre-built artifacts (e.g. \`dist/\`) exist in the\n` +
          `# source. If they do not, the resulting image will not be runnable. The\n` +
          `# companion .dockerignore intentionally does NOT exclude \`dist/\`.\n`;

  return top + body;
}

// ─────────────────────────────────────────────────────────────────────────────
// .dockerignore — two variants (DOCKER-AC-007 confirms invariance across PMs)
// ─────────────────────────────────────────────────────────────────────────────
function renderDockerignoreMulti(): string {
  return (
    `# Generated by pipe-editor v0.1.0 from a Pipeline IR.\n` +
    `# Excludes host files that should not enter the container image. \`dist/\`\n` +
    `# is excluded because the builder stage rebuilds it from source.\n` +
    `\n` +
    `.git\n` +
    `.gitignore\n` +
    `.dockerignore\n` +
    `Dockerfile\n` +
    `node_modules\n` +
    `dist\n` +
    `.env\n` +
    `.env.*\n` +
    `*.log\n` +
    `coverage\n`
  );
}

function renderDockerignoreSingle(): string {
  return (
    `# Generated by pipe-editor v0.1.0 from a Pipeline IR.\n` +
    `# Excludes host files that should not enter the container image. \`dist/\`\n` +
    `# is NOT excluded — the single-stage image relies on pre-built artifacts\n` +
    `# from the source.\n` +
    `\n` +
    `.git\n` +
    `.gitignore\n` +
    `.dockerignore\n` +
    `Dockerfile\n` +
    `node_modules\n` +
    `.env\n` +
    `.env.*\n` +
    `*.log\n` +
    `coverage\n`
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
function baseImageFor(ir: PipelineIR): string {
  // v1: node runtime only. Pinned to <name>:<major>-alpine (no :latest).
  // DOCKER-FR-005.
  return `node:${ir.project.runtime.version}-alpine`;
}

function lockfileFor(pm: PackageManagerName): string {
  switch (pm) {
    case 'npm':
      return 'package-lock.json';
    case 'pnpm':
      return 'pnpm-lock.yaml';
    case 'yarn':
      return 'yarn.lock';
  }
}

function needsCorepack(pm: PackageManagerName): boolean {
  // npm ships with Node; pnpm and yarn need corepack to be activated for the
  // pinned version to be available.
  return pm !== 'npm';
}

/**
 * Whether this IR's install stage froze against a lockfile.
 *
 * GEN-04 — the generator cannot see the filesystem, but the detector already
 * decided this question when it emitted the install stage (DR-007), and the
 * IR is the source of truth (ADR-0003). Reading the decision back beats
 * re-deriving it from a table that cannot know whether a lockfile exists.
 * An IR with no install stage keeps the frozen default: it is the correct
 * command for the overwhelmingly common case, and a hand-built IR that
 * dropped its install stage has said nothing either way.
 */
function usesFrozenInstall(ir: PipelineIR): boolean {
  const install = ir.stages.find((s) => s.id === 'install');
  if (install === undefined || install.steps.length === 0) return true;
  const text = install.steps.map((s) => s.run).join('\n');
  if (/\bnpm\s+ci\b|--frozen-lockfile|--immutable/.test(text)) return true;
  return !/\b(npm|pnpm|yarn)\s+install\b/.test(text);
}

function installCommand(
  pm: PackageManagerName,
  prodOnly: boolean,
  frozen = true,
): string {
  if (!frozen) {
    // No lockfile to freeze against; `npm ci` and `--frozen-lockfile` abort
    // outright in that state, so a resolving install is the only command
    // that can run. The header says the build is not reproducible.
    switch (pm) {
      case 'npm':
        return prodOnly ? 'npm install --omit=dev' : 'npm install';
      case 'pnpm':
        return prodOnly ? 'pnpm install --prod' : 'pnpm install';
      case 'yarn':
        return prodOnly ? 'yarn install --production' : 'yarn install';
    }
  }
  return frozenInstallCommand(pm, prodOnly);
}

function frozenInstallCommand(pm: PackageManagerName, prodOnly: boolean): string {
  // Install table from the spec — the contents of the `RUN <install>` line.
  // For pnpm/yarn, a standalone `RUN corepack enable` precedes this in each
  // stage; the inline prefix would be redundant.
  switch (pm) {
    case 'npm':
      return prodOnly ? 'npm ci --omit=dev' : 'npm ci';
    case 'pnpm':
      return prodOnly ? 'pnpm install --frozen-lockfile --prod' : 'pnpm install --frozen-lockfile';
    case 'yarn':
      return prodOnly ? 'yarn install --frozen-lockfile --production' : 'yarn install --frozen-lockfile';
  }
}

function getBuildStage(ir: PipelineIR): Stage {
  const s = ir.stages.find((st) => st.id === 'build');
  // resolveBuildMode guaranteed multi-stage only when build has ≥ 1 step, so
  // the lookup cannot be undefined here. This is defensive.
  if (s === undefined) throw new Error('internal: build stage missing in multi-stage path');
  return s;
}

function buildCommandFromStage(build: Stage): string {
  // DOCKER-FR-007: emit the build Stage's steps verbatim, joined with `&&`
  // in declared order. The `&&` join collapses status per DOCKER-LIMIT-002.
  return build.steps.map((s) => s.run).join(' && ');
}

function conventionalCmd(ir: PipelineIR): string {
  // Design Decision 2 — convention table.
  return ir.project.language === 'typescript'
    ? '["node", "dist/main.js"]'
    : '["node", "index.js"]';
}
