# Generated by pipe-editor v0.1.0 from a Pipeline IR.
# Source: project "node-pnpm-nest-basic" — runtime: node 20 — packageManager: pnpm 9.
# This Dockerfile is portable: `docker build .` works with no pipe-editor
# tooling present. A companion `.dockerignore` is generated alongside.

# ─── Builder stage ──────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Enable corepack so the pinned pnpm version is available.
RUN corepack enable

# Copy manifest and lockfile first so dependency installation caches
# independently of source changes.
COPY package.json pnpm-lock.yaml ./

# Install all dependencies (including dev) for the build.
RUN pnpm install --frozen-lockfile

# Copy the rest of the project source. The companion .dockerignore excludes
# node_modules, dist, .git, .env, etc., so this COPY is safe.
COPY . .

# Build command from the IR's `build` Stage.
RUN pnpm build

# ─── Runtime stage ──────────────────────────────────────────────────────────
FROM node:20-alpine AS runtime

WORKDIR /app

RUN corepack enable

# Install production-only dependencies. We re-install from the lockfile
# here rather than `COPY --from=builder node_modules` and prune: a fresh
# install is deterministic in one command, while prune semantics differ
# subtly across package managers and versions.
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

# Copy build artifacts from the builder stage.
COPY --from=builder /app/dist ./dist

# CMD inferred from the Node/NestJS convention (DOCKER-LIMIT-001).
CMD ["node", "dist/main.js"]
