// GitHub Actions workflow generator.
//
// Semantics mirror the local Executor as closely as GitHub allows:
// every non-docker-build stage of the EFFECTIVE chain runs as a step
// of ONE job inside the stage container, so the workspace is shared
// across stages exactly like the Executor's /workspace mount.
// docker-build (delegated locally) becomes its own job on the VM
// runner, where the docker CLI is available.
//
// The document is built as a plain object and serialized by js-yaml
// (GEN-02) — see yaml-doc.ts for why hand-written YAML was wrong.

import { sanitizeForComment } from '../docker-naming';
import { computeEffectiveChain, PipelineIR, Stage } from '../ir';
import { CiExportArtifact } from './types';
import { dumpYaml, withHeader } from './yaml-doc';

interface WorkflowStep {
  uses?: string;
  name?: string;
  env?: Record<string, string>;
  run?: string;
}

interface WorkflowJob {
  'runs-on': string;
  needs?: string;
  container?: { image: string };
  steps: WorkflowStep[];
}

export function generateGithubActions(ir: PipelineIR): CiExportArtifact {
  const effective = computeEffectiveChain(ir);
  const live = effective.filter((s) => s.id !== 'docker-build');
  const dockerBuild = effective.find((s) => s.id === 'docker-build');
  const branches = ir.triggers?.[0]?.branches?.length ? ir.triggers[0].branches : ['main'];
  const pm = ir.project.packageManager.name;
  // A dedicated corepack step is only needed when no stage command
  // already enables it itself (the detector's install command does).
  const needsCorepack =
    (pm === 'pnpm' || pm === 'yarn') &&
    !live.some((s) => stageScript(s).includes('corepack enable'));
  const image = live[0]?.container.image ?? null;

  const header = [
    'Generated by pipe-editor v0.1.0 from a Pipeline IR.',
    `Project: ${sanitizeForComment(ir.project.name)}. Portable: commit as .github/workflows/ci.yml.`,
    'Stages run as steps of one job so the workspace is shared across',
    'stages — the same semantics pipe-editor uses when running locally.',
  ];

  const jobs: Record<string, WorkflowJob> = {};

  if (live.length > 0) {
    const steps: WorkflowStep[] = [{ uses: 'actions/checkout@v4' }];
    if (needsCorepack) {
      steps.push({
        name: `Enable corepack (${pm} is corepack-managed)`,
        run: 'corepack enable',
      });
    }
    for (const stage of live) {
      // GEN-06: a stage that asked for a different image does not get one
      // here, because a shared workspace needs a single container. The note
      // lives in the header so the information survives without the file
      // having to carry YAML comments the serializer cannot emit.
      if (image !== null && stage.container.image !== image) {
        header.push(
          '',
          `NOTE: stage "${sanitizeForComment(stage.id, 40)}" declared image ` +
            `${sanitizeForComment(stage.container.image, 60)}; this workflow runs every`,
          `stage in ${sanitizeForComment(image, 60)} so they share one workspace.`,
          'Split the stages into separate jobs if that isolation matters.',
        );
      }
      const step: WorkflowStep = { name: stage.name };
      const env = mergedEnv(stage);
      if (env !== null) step.env = env;
      step.run = stageScript(stage);
      steps.push(step);
    }
    jobs.pipeline = {
      'runs-on': 'ubuntu-latest',
      ...(image !== null ? { container: { image } } : {}),
      steps,
    };
  }

  if (dockerBuild !== undefined) {
    jobs['docker-build'] = {
      'runs-on': 'ubuntu-latest',
      ...(live.length > 0 ? { needs: 'pipeline' } : {}),
      steps: [
        { uses: 'actions/checkout@v4' },
        { name: dockerBuild.name, run: stageScript(dockerBuild) },
      ],
    };
  }

  if (live.length === 0 && dockerBuild === undefined) {
    header.push(
      '',
      'The effective chain is empty — every stage is disabled.',
      'Re-enable stages in pipe-editor and re-export.',
    );
    jobs.noop = {
      'runs-on': 'ubuntu-latest',
      steps: [{ run: 'echo "pipeline is empty — nothing to do"' }],
    };
  }

  const doc = { name: 'CI', on: { push: { branches } }, jobs };

  return {
    provider: 'github-actions',
    filename: '.github/workflows/ci.yml',
    content: withHeader(header, dumpYaml(doc, 'github-actions')),
  };
}

/**
 * One IR stage becomes one `run:` block, its steps on separate lines.
 *
 * Newline-separated, never ` && `-joined: a step whose command contains a
 * `#` comment or a shell control structure is mangled by `&&` (the same
 * defect as IMP-01, in the export direction). GitHub runs `run:` under
 * `bash -e`, so a failing line still stops the block — the failure
 * semantics ` && ` was providing are preserved.
 */
function stageScript(stage: Stage): string {
  return stage.steps.map((s) => s.run).join('\n');
}

function mergedEnv(stage: Stage): Record<string, string> | null {
  const env: Record<string, string> = {};
  // IMP-02: copy, never alias a step's own env object into the result.
  for (const step of stage.steps) Object.assign(env, { ...step.env });
  return Object.keys(env).length > 0 ? env : null;
}
