// GitLab CI generator.
//
// GitLab jobs get a fresh workspace each, so the shared-workspace
// semantics of the local Executor are approximated with a pipeline-
// scoped cache keyed on the lockfile (node_modules + build output
// travel between jobs). Each stage keeps its own container image —
// GitLab supports per-job images natively.
//
// The document is built as a plain object and serialized by js-yaml
// (GEN-02) — see yaml-doc.ts for why hand-written YAML was wrong.

import { sanitizeForComment } from '../docker-naming';
import { computeEffectiveChain, PipelineIR, Stage } from '../ir';
import { CiExportArtifact } from './types';
import { dumpYaml, withHeader } from './yaml-doc';

interface GitlabJob {
  stage: string;
  extends?: string;
  image?: string;
  services?: string[];
  variables?: Record<string, string>;
  script: string[];
}

/** Hidden job holding the shared cache; jobs pull it in with `extends`. */
const CACHE_TEMPLATE_KEY = '.workspace-cache';

export function generateGitlabCi(ir: PipelineIR): CiExportArtifact {
  const effective = computeEffectiveChain(ir);
  const live = effective.filter((s) => s.id !== 'docker-build');
  const dockerBuild = effective.find((s) => s.id === 'docker-build');
  const pm = ir.project.packageManager.name;
  const needsCorepack = pm === 'pnpm' || pm === 'yarn';
  const lockfile =
    pm === 'pnpm' ? 'pnpm-lock.yaml' : pm === 'yarn' ? 'yarn.lock' : 'package-lock.json';

  const header = [
    'Generated by pipe-editor v0.1.0 from a Pipeline IR.',
    `Project: ${sanitizeForComment(ir.project.name)}. Portable: commit as .gitlab-ci.yml.`,
    'A pipeline-scoped cache stands in for the shared workspace the',
    'local Executor gives consecutive stages.',
  ];

  const stageNames = [...live.map((s) => s.id), ...(dockerBuild ? ['docker-build'] : [])];

  if (stageNames.length === 0) {
    header.push(
      '',
      'The effective chain is empty — every stage is disabled.',
      'Re-enable stages in pipe-editor and re-export.',
    );
    const doc = {
      stages: ['noop'],
      noop: { stage: 'noop', script: ['echo "pipeline is empty — nothing to do"'] },
    };
    return artifact(withHeader(header, dumpYaml(doc, 'gitlab-ci')));
  }

  const usesCache = live.length > 0;
  if (usesCache) {
    header.push('', 'node_modules and the build output travel between jobs via cache.');
  }

  const doc: Record<string, unknown> = { stages: stageNames };
  if (usesCache) {
    // `extends` rather than a YAML anchor: it is GitLab's own mechanism and
    // it serializes as plain data, so the document stays a plain object the
    // parse-back check can compare (anchors would need js-yaml refs, whose
    // generated names are worse to read than the key they replace).
    doc[CACHE_TEMPLATE_KEY] = {
      cache: { key: { files: [lockfile] }, paths: ['node_modules/', 'dist/'] },
    };
  }

  for (const stage of live) {
    const job: GitlabJob = {
      stage: stage.id,
      ...(usesCache ? { extends: CACHE_TEMPLATE_KEY } : {}),
      image: stage.container.image,
      script: [],
    };
    const env = mergedEnv(stage);
    if (env !== null) job.variables = env;
    if (needsCorepack && !stage.steps.some((s) => s.run.includes('corepack enable'))) {
      job.script.push('corepack enable');
    }
    // One IR step per script entry; GitLab's script IS a list, so a
    // multi-line command stays one entry and js-yaml gives it a block
    // scalar rather than a broken quoted string.
    for (const step of stage.steps) job.script.push(step.run);
    doc[stage.id] = job;
  }

  if (dockerBuild !== undefined) {
    // GEN-05: the image comes from the IR, which is the source of truth
    // (ADR-0003). This generator used to hardcode docker:27 while DR-011
    // had put docker:25 in the document — the generator overruling the IR
    // is exactly what ADR-0003 forbids. The dind service is derived from
    // the same reference so the two cannot drift apart.
    const image = dockerBuild.container.image;
    header.push(
      '',
      `The docker-build job runs in ${sanitizeForComment(image, 60)} with a`,
      'Docker-in-Docker service. That REQUIRES a GitLab runner registered in',
      'privileged mode; on a shared runner without it, this job will fail.',
    );
    doc['docker-build'] = {
      stage: 'docker-build',
      image,
      services: [dindServiceFor(image)],
      script: dockerBuild.steps.map((s) => s.run),
    };
  }

  return artifact(withHeader(header, dumpYaml(doc, 'gitlab-ci')));
}

/**
 * The `-dind` companion for a docker image reference.
 *
 * `docker:25` becomes `docker:25-dind`. A digest-pinned or untagged
 * reference has no tag to extend, so fall back to the plain `docker:dind`
 * rather than producing a reference that cannot resolve.
 */
export function dindServiceFor(image: string): string {
  const match = /^([^@:]+):([^@]+)$/.exec(image);
  if (match === null) return 'docker:dind';
  return `${match[1]}:${match[2]}-dind`;
}

function artifact(content: string): CiExportArtifact {
  return {
    provider: 'gitlab-ci',
    filename: '.gitlab-ci.yml',
    content: content.trimEnd() + '\n',
  };
}

function mergedEnv(stage: Stage): Record<string, string> | null {
  const env: Record<string, string> = {};
  // IMP-02: copy, never alias a step's own env object into the result.
  for (const step of stage.steps) Object.assign(env, { ...step.env });
  return Object.keys(env).length > 0 ? env : null;
}
