# Generated by pipe-editor v0.1.0 from a Pipeline IR.
# Source: project "node-npm-nest-basic" — runtime: node 20 — packageManager: npm 10.
# This Dockerfile is portable: `docker build .` works with no pipe-editor
# tooling present. A companion `.dockerignore` is generated alongside.

# ─── Builder stage ──────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Copy manifest and lockfile first so dependency installation caches
# independently of source changes.
COPY package.json package-lock.json ./

# Install all dependencies (including dev) for the build.
RUN npm ci

# Copy the rest of the project source. The companion .dockerignore excludes
# node_modules, dist, .git, .env, etc., so this COPY is safe.
COPY . .

# Build command from the IR's `build` Stage.
RUN npm run build

# ─── Runtime stage ──────────────────────────────────────────────────────────
FROM node:20-alpine AS runtime

WORKDIR /app

# Install production-only dependencies. We re-install from the lockfile
# here rather than `COPY --from=builder node_modules` and prune: a fresh
# install is deterministic in one command, while prune semantics differ
# subtly across package managers and versions.
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Copy build artifacts from the builder stage.
COPY --from=builder /app/dist ./dist

# CMD inferred from the Node/NestJS convention (DOCKER-LIMIT-001).
CMD ["node", "dist/main.js"]
