# Generated by pipe-editor v0.1.0 from a Pipeline IR.
# Source: project "node-pnpm-nest-basic" — runtime: node 20 — packageManager: pnpm 9.
#
# NOTE: the source IR did not declare a `build` Stage; nothing was built.
# The image assumes pre-built artifacts (e.g. `dist/`) exist in the
# source. If they do not, the resulting image will not be runnable. The
# companion .dockerignore intentionally does NOT exclude `dist/`.

FROM node:20-alpine

WORKDIR /app

RUN corepack enable

# Install production-only dependencies.
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

# Copy the project source. The companion .dockerignore excludes
# node_modules, .git, .env, etc., but intentionally keeps `dist/` so
# pre-built artifacts reach the image.
COPY . .

# CMD inferred from the Node/NestJS convention (DOCKER-LIMIT-001).
CMD ["node", "dist/main.js"]
